# ============================================================
# Step 3 of 3 - Figure 2 main panels (R2 + remaining)
# In Vivo Combinatorial Cas12a CRISPR Screen
# Breast Cancer Lung Metastasis (Day 3 vs. Day 18)
# ============================================================
# Driver: scripts/make_figure_2.R
# Depends on output/tables/ produced by Steps 1 and 2.
#
# MAIN-FIGURE PANELS generated by THIS script (final A-I lettering):
#   Fig2C  - Sample PCA across all conditions            (Fig2C_PCA)
#   Fig2D  - Rank plot of all R1 crRNA pairs             (Fig2D_rank_plot)
#   Fig2G  - R2 volcano (2nd-round 17x17 pair frequency) (Fig2G_volcano)
#   Fig2H  - R2 GI Z-score heatmap                       (Fig2H_GI_heatmap)
#   Fig2I  - Strong-edge GI network of the R2 genes      (Fig2I_GI_network)
#
# SUPPLEMENTARY panel generated by THIS script (written to _supplementary/):
#   SuppFig2Q - Functional-module epistasis pattern      (SuppFig2Q_module_epistasis)
#
# MAIN-FIGURE PANELS from other scripts:
#   Fig2E  - Guide-level LFC distribution  (scripts/01_prepare_r1_gi_tables.R)
#   Fig2A/B/F - external (Illustrator schematic; microscopy; GI-score cartoon)
#
# The spectral embedding and the within-vs-cross forest plot were MOVED OUT of
# the main figure in the A-I revision; they are now SuppFig2J and SuppFig2K and
# are still produced by scripts/02_r1_modules.R.
#
# RETIRED / NOT SHOWN (exploratory variants, not part of any figure; code kept
# only as a legacy snapshot in archive/scripts_supplementary/): Fig2Ma, Fig2N/Na
# (this script), the module pathway-leaning dotplot and 3x3 module-pair heatmap
# (02_r1_modules.R), the STRING PPI network (20_*), and the PPI-vs-GI overlap
# (30_*). The STRING/PPI comparison was not pursued. Supplementary Figure 2 is the
# Cas12a-system validation + screen-QC figure (scripts/make_supp_figure_2.R).
#
# DATA DEPENDENCIES:
#   data/raw/R1_construct_counts.csv   — R1 per-construct counts, 20 samples
#   data/derived/R2_Day18.gene_summary.txt — MAGeCK gene summary, 2nd round
#   output/tables/R2_GI_derived.csv        — GI values, built by 04_r2_derive_gi.R
#   output/tables/all_gene_pairs_full.csv  — 1st-round aggregated gene-pair stats
#   output/tables/GI_scores_all_dualKO.csv — 1st-round dual-KO GI scores + FDR
#   output/tables/module_assignments.csv   — spectral clustering module membership
#
# USAGE:
#   Rscript scripts/03_main_panels.R
#   (or source() / run interactively in RStudio)
#
# All figures are saved to: output/figures/
# ============================================================


# ============================================================
# SECTION 0: Setup
# ============================================================

# ── 0.1  Required packages ────────────────────────────────
required_pkgs <- c(
  "ggplot2", "ggrepel", "dplyr",
  "readxl", "pheatmap",
  "igraph", "ggraph", "tidygraph",
  "stringr", "tidyr"
)
missing_pkgs <- setdiff(required_pkgs, rownames(installed.packages()))
if (length(missing_pkgs) > 0) {
  message("Installing missing packages: ", paste(missing_pkgs, collapse = ", "))
  install.packages(missing_pkgs, repos = "https://cloud.r-project.org")
}

library(ggplot2)
library(ggrepel)
library(dplyr)
library(readxl)
library(pheatmap)
library(igraph)
library(ggraph)
library(tidygraph)
library(stringr)
library(tidyr)

# ── 0.2  Path configuration ───────────────────────────────
source(here::here("R", "paths.R"))
source(here::here("R", "palettes.R"))
source(here::here("R", "helpers.R"))
# Panels are authored at final placed size; see R/theme_pub.R.
source(here::here("R", "theme_pub.R"))

OUTPUT_DIR   <- OUT_TABLES
FIG_DIR      <- OUT_FIGS

# ── 0.3  Shared color palette ─────────────────────────────
COL_ENR <- "#d62728"   # enriched  (FDR < 0.05, LFC > 0)
COL_DEP <- "#1f77b4"   # depleted  (FDR < 0.05, LFC < 0)
COL_NT  <- "#ff7f0e"   # NT×NT control
COL_BG  <- "#aaaaaa"   # not significant

# Spectral module colors (Module 0 / 1 / 2)
MODULE_COLORS <- c("0" = "#E41A1C", "1" = "#377EB8", "2" = "#4DAF4A")

# GI_Z_LIMITS, GI_BLUE, GI_RED are provided by R/palettes.R (shared with Supp Fig 2L).
GI_STRONG_Z_THRESHOLD <- 1.5

message("\n=== Figure 2 Consolidated R Script ===")
message("Repo root  : ", REPO_ROOT)
message("Output dir : ", FIG_DIR, "\n")


# ============================================================
# SECTION 1: Fig2C — Sample PCA
# ============================================================
# BIOLOGICAL QUESTION:
#   Do the sgRNA count profiles separate by experimental condition
#   (in vitro vs. in vivo, early vs. late time points)?
#   PCA on guide-level normalized counts reveals global library
#   representation shifts across conditions and validates that
#   biological replicates cluster together.
#
# INPUT:  R1_construct_counts.csv
#   Rows = sgRNA constructs; columns = the 20 sequenced samples: three technical
#   replicates of the injected pool (Cell_Day0, _2, _3), five in vitro day-14
#   cultures, six day-3 lungs and six day-18 lungs.
#
#   This panel previously ran on Cas12a_full_count_PCA.csv, which mislabelled its
#   in vitro day-14 cultures as day 18, carried a separate in vivo day-14 group
#   under the names Mice_Day18_7..12, and held only four of the six day-3 mice.
#   See data/raw/deprecated/README.md.
#
# METHOD (ported from the analysis package shipped with the corrected counts):
#   1. CPM normalization, each sample scaled to 1e7 total reads.
#   2. Representation gate: keep constructs with raw Cell_Day0 >= DAY0_MIN.
#   3. log2(CPM + 1).
#   4. prcomp on samples x constructs, features mean-centred, no rescaling.
#   5. 95% confidence ellipses (stat_ellipse) per group with >= 3 replicates.
# ============================================================

message("--- Fig2C: Sample PCA ---")

# Must match DAY0_MIN in scripts/01_prepare_r1_gi_tables.R: one definition of
# "present in the library" governs the whole figure.
PCA_DAY0_MIN <- 5

# -- 1.1  Group metadata ----------------------------------
group_order <- c("Cell_Injection", "In_Vitro_Day14",
                 "In_Vivo_Day3", "In_Vivo_Day18")

# group_colors is provided by R/palettes.R.

group_info <- c(
  setNames(rep("Cell_Injection", 3), c("Cell_Day0", "Cell_Day0_2", "Cell_Day0_3")),
  setNames(rep("In_Vitro_Day14", 5), paste0("Cell_Day14_", 1:5)),
  setNames(rep("In_Vivo_Day3",   6), paste0("Mice_Day3_",  1:6)),
  setNames(rep("In_Vivo_Day18",  6), paste0("Mice_Day18_", 1:6))
)

# -- 1.2  Load counts -------------------------------------
pca_raw <- read.csv(
  raw("R1_construct_counts.csv"),
  header = TRUE, stringsAsFactors = FALSE, check.names = FALSE
)

sample_cols <- intersect(names(group_info), colnames(pca_raw))
missing_s   <- setdiff(names(group_info), colnames(pca_raw))
if (length(missing_s) > 0)
  stop("Samples defined but not found in the count matrix: ",
       paste(missing_s, collapse = ", "))
stopifnot(length(sample_cols) == 20L)

# -- 1.3  Pre-process for PCA -----------------------------
mat <- as.matrix(pca_raw[, sample_cols, drop = FALSE])
storage.mode(mat) <- "double"
mat[is.na(mat)] <- 0

# CPM to a common depth, so samples sequenced at different depth are comparable.
mat <- sweep(mat, 2, colSums(mat), "/") * 1e7

# Representation gate. Half the library is absent from the injected pool, and
# those constructs contribute only dropout noise to the sample geometry. Gated
# on the pooled sum of the three Cell_Day0 technical replicates, matching the
# DAY0_MIN gate in scripts/01_prepare_r1_gi_tables.R (one definition of
# "present in the library" governs the whole figure).
day0_pooled <- rowSums(pca_raw[, c("Cell_Day0", "Cell_Day0_2", "Cell_Day0_3")])
gate <- day0_pooled >= PCA_DAY0_MIN
mat  <- mat[gate, , drop = FALSE]
message(sprintf("  constructs with pooled Cell_Day0 >= %d: %d of %d",
                PCA_DAY0_MIN, nrow(mat), nrow(pca_raw)))

mat <- log2(mat + 1)
keep <- apply(mat, 1, function(x) sd(x) > 0)
mat  <- mat[keep, , drop = FALSE]

pca_input <- t(mat)               # samples x constructs

# -- 1.4  Run PCA -----------------------------------------
# Features are mean-centred and not rescaled: constructs are already on one
# log-CPM scale, and rescaling would give the sparsest constructs the same
# leverage as the well-measured ones.
pca_res  <- prcomp(pca_input, center = TRUE, scale. = FALSE)

# Principal-component signs are arbitrary and can flip between BLAS builds, which
# would mirror the panel without changing anything it means. Both axes are pinned
# to a fixed orientation so the placed panel is reproducible: the injected pool
# sits on the positive side of PC1, and the day-18 lungs on the positive side of
# PC2.
.sc <- pca_res$x
if (.sc["Cell_Day0", "PC1"] < 0) { .sc[, "PC1"] <- -.sc[, "PC1"] }
.d18 <- paste0("Mice_Day18_", 1:6)
if (mean(.sc[.d18, "PC2"]) < 0) { .sc[, "PC2"] <- -.sc[, "PC2"] }
pca_res$x <- .sc

pca_df   <- as.data.frame(pca_res$x)
pca_df$Sample <- rownames(pca_df)
pca_df$Group  <- factor(group_info[pca_df$Sample], levels = group_order)
pct_var  <- round((pca_res$sdev^2) / sum(pca_res$sdev^2) * 100, 2)

# Numerical source data for Figure 2C: exact PC1/PC2 point coordinates and group
# assignments supplied to ggplot below. The variance percentages reproduce the
# axis labels; gate metadata records the feature set used to calculate the PCA.
pca_source_data <- pca_df[, c("Sample", "Group", "PC1", "PC2")]
pca_source_data$PC1_variance_percent <- pct_var[1]
pca_source_data$PC2_variance_percent <- pct_var[2]
pca_source_data$n_constructs_used <- nrow(mat)
pca_source_data$pooled_day0_min_reads <- PCA_DAY0_MIN
write.csv(
  pca_source_data,
  file.path(OUTPUT_DIR, "Fig2C_PCA_source_data.csv"),
  row.names = FALSE,
  quote = FALSE
)

# ── 1.5  Plot helper ─────────────────────────────────────
plot_pca <- function(df, pc_x = 1, pc_y = 2) {
  xc <- paste0("PC", pc_x); yc <- paste0("PC", pc_y)
  ellipse_df <- df |>
    group_by(Group) |>
    filter(n() >= 3, qr(cbind(.data[[xc]], .data[[yc]]))$rank >= 2) |>
    ungroup()
  ggplot(df, aes(x = .data[[xc]], y = .data[[yc]])) +
    geom_point(aes(color = Group, shape = Group), size = SZ_POINT) +
    # Normal-theory ellipse rather than the t-based default: with five in vitro
    # replicates the default draws a region several times the spread of the data.
    stat_ellipse(data = ellipse_df, aes(fill = Group), geom = "polygon",
                 type = "norm", level = 0.80, alpha = 0.15,
                 show.legend = FALSE) +
    scale_color_manual(values = group_colors, drop = FALSE) +
    scale_fill_manual(values = group_colors, drop = FALSE) +
    scale_shape_manual(values = c(
      "Cell_Injection" = 16, "In_Vitro_Day14" = 16,
      "In_Vivo_Day3" = 17, "In_Vivo_Day18" = 15
    ), drop = FALSE) +
    xlab(paste0(xc, " (", pct_var[pc_x], "%)")) +
    ylab(paste0(yc, " (", pct_var[pc_y], "%)")) +
    ggtitle("PCA \u2014 sgRNA library representation") +
    theme_panel() +
    theme(panel.grid.major.x = element_line(colour = "#eeeeee", linewidth = 0.2))
}

p2b <- plot_pca(pca_df)

save_panel(p2b, file.path(FIG_DIR, "Fig2C_PCA.pdf"))

message("  Saved Fig2C_PCA.pdf/.png")


# ============================================================
# SECTION 2: Fig2D — Rank Plot
# ============================================================
# BIOLOGICAL QUESTION:
#   Which gene pairs (single-KO or dual-KO) are most significantly
#   enriched or depleted in lung metastases compared to input?
#   The rank plot orders all pairs by their NT-corrected weighted
#   mean log2FC, annotates statistical significance (FDR < 0.05), and
#   labels the top 8 enriched pairs for Fig2D (top 10 for SuppFig2N).
#
# INPUT:  R1_enrichment_day0_invivo.csv  and  R1_enrichment_day0_invitro.csv
#   Generated by 01_prepare_r1_gi_tables.R. One row per gene pair with:
#   - weighted_mean_lfc : random-effects weighted mean log2FC (Nt x Nt-corrected)
#   - fdr               : Benjamini-Hochberg FDR (Wald test on aggregated LFC)
#   - pair_type         : "single_KO" | "dual_KO" | "nt_nt"
#
#   Enrichment is referenced to the injected pool rather than to day 3. Selection
#   is the question, so the colonization loss belongs in the measurement, and no
#   term is subtracted twice as it would be in an interaction score. See the long
#   note in 01_prepare_r1_gi_tables.R for why the interaction analysis keeps the
#   day-3 baseline instead.
#
# METHOD:
#   Pairs ranked in descending order of weighted_mean_lfc.
#   red = enriched (FDR < 0.05, LFC > 0), blue = depleted, orange = Nt x Nt
#   control, grey = not significant. ggrepel labels the top enriched pairs
#   (8 for Fig2D, 10 for SuppFig2N) and the Nt x Nt control.
#
# NOTE ON THE Nt x Nt CORRECTION:
#   Every LFC has the Nt x Nt reference subtracted, so that point sits at zero by
#   construction. The reference is 2.2813 for the in vivo contrast and 1.4112 for
#   the in vitro one.
#
#   The same routine draws the in vitro specificity control, supplementary panel
#   M: day-14 cultures against the same pool. If the enrichment seen in vivo were
#   proliferation rather than metastasis, it would appear there too.
# ============================================================

message("--- Fig2D: Rank Plot ---")

FDR_THRESH <- 0.05
N_LABEL    <- 10

make_rank_plot <- function(tbl, y_lab, title, subtitle, out_dir, out_stem,
                           fdr_thresh = FDR_THRESH, n_label = N_LABEL) {
  gp <- read.csv(file.path(OUTPUT_DIR, tbl), stringsAsFactors = FALSE) |>
    arrange(desc(weighted_mean_lfc)) |>
    mutate(
      rank        = seq_len(n()),
      label_clean = pair_label(gene_pair),
      is_nt       = pair_type == "nt_nt",
      category    = case_when(
        is_nt                                     ~ "NT control",
        fdr < fdr_thresh & weighted_mean_lfc > 0 ~ "Enriched",
        fdr < fdr_thresh & weighted_mean_lfc < 0 ~ "Depleted",
        TRUE                                      ~ "Not significant"
      ),
      category = factor(category, levels = c("Enriched", "Depleted",
                                             "NT control", "Not significant"))
    )
  n_enr <- sum(gp$category == "Enriched")
  n_dep <- sum(gp$category == "Depleted")
  # Labelling only dual-knockout pairs: the single-knockout controls are the
  # reference the interaction analysis is built on, not findings of this panel.
  top_enr <- gp |> filter(category == "Enriched", pair_type == "dual_KO") |>
    slice_head(n = n_label)
  nt_row  <- gp |> filter(is_nt) |> slice_head(n = 1)
  n_total <- nrow(gp)

  col_map   <- c("Enriched" = COL_ENR, "Depleted" = COL_DEP,
                 "NT control" = COL_NT, "Not significant" = COL_BG)
  label_map <- c(
    "Enriched"        = paste0("Enriched  FDR<", fdr_thresh, "  (n=", n_enr, ")"),
    "Depleted"        = paste0("Depleted  FDR<", fdr_thresh, "  (n=", n_dep, ")"),
    "NT control"      = paste0("Nt", PAIR_SEP, "Nt control"),
    "Not significant" = "Not significant")

  p <- ggplot(gp, aes(rank, weighted_mean_lfc, color = category)) +
    geom_hline(yintercept = 0, color = "black", linewidth = LW_RULE) +
    geom_point(data = filter(gp, category == "Not significant"),
               size = SZ_POINT_SM, alpha = 0.45, shape = 16) +
    geom_point(data = filter(gp, category != "Not significant"),
               size = SZ_POINT_HL, alpha = 0.8, shape = 16) +
    {if (nrow(top_enr) > 0)
      geom_text_repel(
        data = top_enr, aes(label = label_clean),
        color = COL_ENR, size = pt(FS_LABEL), fontface = "plain",
        nudge_x = n_total * 0.30, direction = "y", hjust = 0,
        segment.color = COL_ENR, segment.size = 0.2, segment.alpha = 0.6,
        min.segment.length = 0, box.padding = 0.14, point.padding = 0.06,
        max.overlaps = Inf, force = 2, seed = 42, show.legend = FALSE,
        # Labels are held above the zero line so the lowest of them cannot sit on
        # the axis rule, which it otherwise does whenever the tenth-ranked pair
        # falls close to zero.
        ylim = c(max(gp$weighted_mean_lfc, na.rm = TRUE) * 0.06, NA))} +
    {if (nrow(nt_row) > 0)
      geom_text_repel(
        data = nt_row, aes(label = label_clean),
        color = COL_NT, size = pt(FS_LABEL), fontface = "plain",
        nudge_x = n_total * 0.10,
        nudge_y = max(gp$weighted_mean_lfc, na.rm = TRUE) * 0.20,
        segment.color = COL_NT, segment.size = 0.25, segment.alpha = 0.85,
        arrow = arrow(length = unit(2, "pt"), type = "closed"),
        min.segment.length = 0, max.overlaps = Inf, seed = 42,
        show.legend = FALSE)} +
    scale_color_manual(values = col_map, labels = label_map, name = NULL,
                       drop = FALSE,
                       guide = guide_legend(override.aes = list(
                         size = 1.1, alpha = 1, shape = 15))) +
    scale_x_continuous(expand = expansion(mult = c(0.01, 0.01))) +
    # WinAnsi has no subscript digits, so the subscript is plotmath rather than
    # the Unicode character. Quoting keeps the words upright: an unquoted
    # plotmath identifier renders italic.
    labs(x = expression("Rank  (by weighted mean log"[2]*"FC)"),
         y = y_lab, title = title, subtitle = subtitle) +
    theme_panel() +
    theme(
      legend.position  = "inside",
      legend.position.inside = c(0.02, 0.02),
      legend.justification = c("left", "bottom"),
      legend.background = element_rect(fill = "white", color = "#cccccc",
                                       linewidth = LW_THIN),
      legend.key.size  = unit(4.5, "pt")
    )
  save_panel(p, file.path(out_dir, paste0(out_stem, ".pdf")))
  message(sprintf("  Saved %s.pdf/.png | %d enriched, %d depleted (FDR<%.2f)",
                  out_stem, n_enr, n_dep, fdr_thresh))
  invisible(p)
}

# Fig2D uses the module default FDR<0.05 but labels only the top 8 enriched
# pairs (rather than the default 10); SuppFig2N (the in vitro control, below)
# keeps both module defaults.
p2c <- make_rank_plot(
  "R1_enrichment_day0_invivo.csv",
  expression("Weighted mean log"[2]*"FC  (Day 18 / Day 0)"),
  "Rank Plot \u2014 All Gene Pairs, in vivo",
  paste0("Nt", PAIR_SEP, "Nt-corrected; FDR<0.05 (BH, random-effects Wald)"),
  FIG_DIR, "Fig2D_rank_plot",
  n_label = 8)

# Supplementary panel M: the in vitro specificity control.
# NOTE: Day 14 here is correct and is not a stale label. The two arms of the
# round-1 screen run to different endpoints: R1_construct_counts.csv carries
# Cell_Day14_* for the cultured arm and Mice_Day18_* for the injected arm.
# Fig2D (in vivo) is therefore Day 18 while this control is Day 14.
if (file.exists(file.path(OUTPUT_DIR, "R1_enrichment_day0_invitro.csv"))) {
  make_rank_plot(
    "R1_enrichment_day0_invitro.csv",
    expression("Weighted mean log"[2]*"FC  (Day 14 / Day 0)"),
    "Rank Plot \u2014 All Gene Pairs, in vitro control",
    "Same library and baseline, cultured rather than injected",
    OUT_SUPP, "SuppFig2N_invitro_rank_plot")
}

# ============================================================
# SECTION 3: Fig2G — Volcano Plot (2nd-round gene summary)
# ============================================================
# BIOLOGICAL QUESTION:
#   In the second-round focused 17×17 library (289 gene pairs,
#   complete coverage of the cross-program interaction landscape),
#   which INDIVIDUAL genes drive the strongest pro-metastatic
#   (enriched) or anti-metastatic (depleted) phenotypes?
#
# INPUT:  R2_Day18.gene_summary.txt
#   MAGeCK gene_summary output. Key columns:
#   - id         : gene name
#   - pos|lfc    : gene-level LFC (positive direction)
#   - pos|p-value: p-value for enrichment
#   - neg|p-value: p-value for depletion
#   Direction-appropriate p-value is selected (pos p-val for LFC ≥ 0,
#   neg p-val for LFC < 0).
#
# METHOD:
#   Standard volcano: x = LFC, y = -log10(p-value).
#   Significance threshold: p < 0.05 (dashed line).
#   Labels: significant genes with |LFC| > 2 (enriched) or < -1.2 (depleted).
# ============================================================

message("--- Fig2G: Volcano Plot ---")

gs_df <- read.table(
  derived("R2_Day18.gene_summary.txt"),
  header = TRUE, sep = "\t", check.names = FALSE
)

# Standardize column names (MAGeCK format uses pipe-delimited headers)
gs_df <- gs_df |>
  rename(
    label    = id,
    lfc      = `pos|lfc`,
    pos_pval = `pos|p-value`,
    neg_pval = `neg|p-value`
  ) |>
  mutate(
    pval        = ifelse(lfc >= 0, pos_pval, neg_pval),
    neg_log10_p = -log10(pval)
  ) |>
  filter(!is.na(pval))

sig_thr <- -log10(0.05)

gs_df <- gs_df |>
  mutate(color_group = case_when(
    neg_log10_p >= sig_thr & lfc > 0  ~ "enriched",
    neg_log10_p >= sig_thr & lfc < 0  ~ "depleted",
    TRUE                               ~ "ns"
  ))

# Label rule is the reference one: the three most significant depleted pairs and
# the eight most significant enriched pairs, ranked by p. The repository's older
# rule selected on fold-change magnitude (lfc > 2 or < -1.2), which labels large
# but non-significant pairs and skips significant ones with modest fold changes.
to_label_vol <- rbind(
  head(gs_df[gs_df$color_group == "depleted", ][
    order(gs_df$pval[gs_df$color_group == "depleted"]), , drop = FALSE], 3),
  head(gs_df[gs_df$color_group == "enriched", ][
    order(gs_df$pval[gs_df$color_group == "enriched"]), , drop = FALSE], 8)
)
to_label_vol <- to_label_vol[!duplicated(to_label_vol$label), , drop = FALSE]

# Numerical source data for Figure 2G: exact volcano coordinates, the
# direction-appropriate p-value, plotted colour class, and final label selection.
gs_source_data <- gs_df |>
  mutate(
    labelled = label %in% to_label_vol$label,
    significance_threshold_p = 0.05
  ) |>
  select(label, num, lfc, pos_pval, neg_pval, pval, neg_log10_p,
         color_group, labelled, significance_threshold_p)
write.csv(
  gs_source_data,
  file.path(OUTPUT_DIR, "Fig2G_volcano_source_data.csv"),
  row.names = FALSE,
  quote = FALSE
)

p2i <- ggplot(gs_df, aes(lfc, neg_log10_p, color = color_group)) +
  geom_point(size = SZ_POINT * 0.8, alpha = 0.85) +
  geom_hline(yintercept = sig_thr, linetype = "dashed",
             color = "gray50", linewidth = LW_THIN) +
  # ggrepel jitters label placement from the RNG, so an unseeded call makes this
  # panel non-deterministic: repeated runs move the labels. Seed immediately
  # before the layer so the rendered panel is byte-reproducible.
  {set.seed(42); geom_text_repel(
    data = to_label_vol, aes(label = pair_label(label)),
    size = pt(FS_LABEL), fontface = "plain", seed = 42,
    segment.size = 0.2, max.overlaps = 20, box.padding = 0.16
  )} +
  annotate("text", x = Inf, y = sig_thr + 0.12,
           label = "p = 0.05", hjust = 1.05, color = "gray50", size = pt(FS_LABEL)) +
  annotate("segment",
           x = min(gs_df$lfc) * 0.3, xend = max(gs_df$lfc) * 1.05,
           y = -0.5, yend = -0.5,
           arrow = arrow(length = unit(2.5, "pt"), type = "closed"),
           color = "#CC3300", linewidth = LW_RULE) +
  annotate("text",
           x    = (min(gs_df$lfc) * 0.3 + max(gs_df$lfc) * 1.05) / 2,
           y    = -0.85,
           label = "enriched crRNA pairs in overt lung mets",
           color = "#CC3300", size = pt(FS_LABEL), fontface = "plain") +
  scale_color_manual(
    values = c("enriched" = "#D84A1B", "depleted" = "#3157D5", "ns" = "#A6A6A6"),
    guide = "none"
  ) +
  labs(
    title = "Volcano \u2014 crRNA frequency change, 2nd round",
    x     = expression("Log"[2]*" Fold Change (LFC)"),
    y     = expression("\u2212Log"[10]*"(p-value)")
  ) +
  theme_panel() +
  theme(axis.title.x = element_text(margin = margin(t = 9)),
        plot.margin  = margin(3, 3, 3, 3)) +
  coord_cartesian(clip = "off")

save_panel(p2i, file.path(FIG_DIR, "Fig2G_volcano.pdf"))

message(sprintf("  Saved Fig2G_volcano.pdf/.png | enriched=%d, depleted=%d, ns=%d",
                sum(gs_df$color_group == "enriched"),
                sum(gs_df$color_group == "depleted"),
                sum(gs_df$color_group == "ns")))


# ============================================================
# SECTION 4: Fig2H — GI Z-score Heatmap
# ============================================================
# BIOLOGICAL QUESTION:
#   Across the 2nd-round 17×17 focused library (Position 1 = cell-
#   autonomous tumor suppressor genes × Position 2 = TME/immune genes),
#   what is the global landscape of pairwise Genetic Interaction (GI)?
#   Hierarchical clustering reveals whether genes group by functional
#   program and whether certain programs share interaction patterns.
#
# INPUT:  output/tables/R2_GI_derived.csv (from 04_r2_derive_gi.R)
#   One row per tested gene pair. Key columns:
#   - Gene1, Gene2 : gene symbols (Position 1 × Position 2)
#   - GI           : raw GI score (observed dual-KO LFC − expected additive)
#   - Count        : number of sgRNA pairs covering this combination
#
# FILTERING:
#   - Exclude Gene × NT pairs (keep true dual-KO only)
#   - Set Count = 1 entries to NA (insufficient guide coverage)
#
# GI Z-SCORE:
#   Sign-preserving normalization: GI_Zscore = GI / SD(GI_all)
#   This preserves the direction of interaction while putting values
#   on a common scale. No mean subtraction — the sign (+ = synergy,
#   − = buffering) carries the primary biological interpretation.
#
# VISUALIZATION:
#   pheatmap with complete-linkage hierarchical clustering on both
#   rows (Gene2, Position 2) and columns (Gene1, Position 1).
#   Color scale: blue (strong buffering) → white (neutral) → red (synergy).
# ============================================================

# The legacy workbook spelled the non-targeting gene "NT" and the derived table
# spells it "Nt", so every NT test here is case-insensitive. An exact `!= "NT"`
# silently let the single-knockout rows into the network and the heatmap.
.is_nt <- function(x) !is.na(x) & tolower(x) %in% c("nt", "ntc")

message("--- Fig2H: GI Z-score Heatmap ---")

gi_df <- read.csv(file.path(OUTPUT_DIR, "R2_GI_derived.csv"),
                  stringsAsFactors = FALSE, check.names = FALSE)
gi_df <- as.data.frame(gi_df)
gi_df <- gi_df[!.is_nt(gi_df$Gene1) & !.is_nt(gi_df$Gene2) & !is.na(gi_df$Gene2), ]

# Sign-preserving Z-score: divide by global SD only
# GI Z is taken from the derived table rather than recomputed. That column is
# CENTRED, (GI - mean) / SD over the true gene pairs; this panel previously
# divided by the SD without centring. Both the centring and the linkage below
# had to match for the dendrogram to agree with the version this figure was
# settled on: neither alone reproduces it.
gi_df$GI_Zscore <- gi_df$GI_Z_Score
global_sd      <- sd(gi_df$GI, na.rm = TRUE)
# No Count mask. `Count` is MAGeCK's `num`, the number of sgRNAs it retained for
# the pair after its own filtering, not a read count and not the number of
# constructs designed: the library designs four per pair while `num` has a median
# of 2. Masking Count == 1 discarded real measurements on an upstream tool's
# filter, so every pair is shown. See HANDOFF_Figure2.html section 3.6.

# Export Z-score table for downstream use
gi_out <- gi_df[!is.na(gi_df$GI_Zscore), c("Gene", "Gene1", "Gene2",
                                              "Count", "GI", "GI_Zscore")]
write.csv(gi_out[order(gi_out$GI_Zscore), ],
          file.path(OUTPUT_DIR, "GI_Zscore_values.csv"), row.names = FALSE)

# Reshape to matrix: Gene1 = columns, Gene2 = rows
mat_wide <- reshape(gi_df[, c("Gene1", "Gene2", "GI_Zscore")],
                    idvar = "Gene2", timevar = "Gene1", direction = "wide")
rownames(mat_wide) <- mat_wide$Gene2
mat_wide$Gene2 <- NULL
colnames(mat_wide) <- sub("GI_Zscore\\.", "", colnames(mat_wide))
gi_mat <- as.matrix(mat_wide)
storage.mode(gi_mat) <- "numeric"

# Symmetric divergent GI-Z color scale for Fig 2H (option F, locked 2026-05).
# ColorBrewer RdBu, symmetric +/-3.5: equal magnitudes read as equal saturation,
# faithful to the buffering-dominated distribution. 0 maps to the RdBu near-white
# midpoint. Values beyond the symmetric limit are clipped (data -3.82 .. +2.18,
# so clipping is effectively lossless). RdBu is perceptually balanced and
# colorblind-safe. Fig 2I keeps its own muted-blue/crimson edge gradient.
# Colour scale is the reference one, not the repository's generic RdBu ramp.
# Two things differ and both are deliberate: the range clips at +/-3 rather than
# +/-3.5, and there is a PURE WHITE NEUTRAL BAND from -0.3 to +0.3, so pairs
# close to no interaction read as blank rather than faintly tinted. That band is
# what makes the strong pairs legible at this panel size; a continuous ramp
# leaves every weak cell carrying colour.
HEAT_LIM <- 3
gi_mat_plot <- pmax(pmin(gi_mat, HEAT_LIM), -HEAT_LIM)
breaks_heat <- c(
  seq(-HEAT_LIM, -0.3, length.out = 61),
  seq(-0.3, 0.3, length.out = 13)[-1],
  seq(0.3, HEAT_LIM, length.out = 61)[-1]
)
colors_heat <- c(
  colorRampPalette(c("#2166AC", "#FFFFFF"))(60),
  rep("#FFFFFF", 12),
  colorRampPalette(c("#FFFFFF", "#B2182B"))(60)
)
leg_breaks  <- c(-3, -2, -1, 0, 1, 2, 3)

# Fixed clustering (locked 2026-05). Count==1 cells (NA) are imputed to 0 for
# the distance calculation ONLY, so the dendrogram is stable and deterministic
# rather than depending on how pheatmap's internal dist() rescales rows with
# NAs. The displayed matrix keeps its NAs (rendered as na_col). Distances are
# computed on the unclipped gi_mat so the ordering does not shift if the clip
# limits change.
gi_mat_impute <- gi_mat
gi_mat_impute[is.na(gi_mat_impute)] <- 0
# Average linkage, not complete. Complete linkage put CDH1 and MUC16 at the top
# of the matrix and split PTEN's synergistic partners across both ends; average
# linkage keeps them together, which is the arrangement this figure was settled
# on. Verified by reproducing the reference row and column order exactly.
hc_row <- hclust(dist(gi_mat_impute),      method = "average")
hc_col <- hclust(dist(t(gi_mat_impute)),   method = "average")

heat_args <- list(
  gi_mat_plot,
  color             = colors_heat,
  breaks            = breaks_heat,
  na_col            = "#D6D6D6",
  cluster_rows      = hc_row,
  cluster_cols      = hc_col,
  border_color      = "#C7C7C7",
  # The heatmap body is the panel, so the 17 x 17 grid is sized to PANEL_PT:
  # 120 / 17 = 7.06 pt per cell. Dendrogram heights and the legend scale with it
  # rather than staying at their old absolute values, which were set for a
  # 476 pt body and would otherwise dwarf the matrix.
  cellwidth         = PANEL_PT / ncol(gi_mat_plot),
  cellheight        = PANEL_PT / nrow(gi_mat_plot),
  fontsize          = MIN_FONT_PT,
  fontsize_row      = MIN_FONT_PT,
  fontsize_col      = MIN_FONT_PT,
  fontfamily        = PANEL_FAMILY,
  angle_col         = 270,
  treeheight_row    = 14, treeheight_col = 14,
  legend_breaks     = leg_breaks,
  legend_labels     = as.character(leg_breaks)
)

# pheatmap sizes its own gtable from the cell dimensions. Measure it and give
# both devices exactly that, so the matrix lands at PANEL_PT square with nothing
# cropped and nothing to rescale at placement.
# pheatmap has to resolve text metrics to build its gtable, so it needs an open
# device; with none it opens R's default one and leaves an Rplots.pdf behind.
# Both the gtable build and the unit conversions below need an open device, so
# they happen inside one. With none open R opens its default, which on a headless
# run writes a stray Rplots.pdf into the working directory.
pdf(nullfile(), width = 8, height = 8, family = PANEL_FAMILY,
    encoding = PDF_ENCODING, useDingbats = FALSE)
ph  <- do.call(pheatmap, c(heat_args, list(filename = NA, silent = TRUE)))
.hw <- sum(grid::convertWidth(ph$gtable$widths,   "in", valueOnly = TRUE))
.hh <- sum(grid::convertHeight(ph$gtable$heights, "in", valueOnly = TRUE))
invisible(dev.off())

# PDF: R's native device, matching every other panel. Helvetica is referenced as
# a standard base-14 font rather than embedded, which keeps the text editable in
# Illustrator with correct metrics; see the note in R/theme_pub.R.
pdf(file.path(FIG_DIR, "Fig2H_GI_heatmap.pdf"), width = .hw, height = .hh,
    family = PANEL_FAMILY, encoding = PDF_ENCODING, useDingbats = FALSE)
grid::grid.newpage(); grid::grid.draw(ph$gtable)
invisible(dev.off())

png(file.path(FIG_DIR, "Fig2H_GI_heatmap.png"), width = .hw, height = .hh,
    units = "in", res = 600, type = "cairo", family = PANEL_FAMILY)
grid::grid.newpage(); grid::grid.draw(ph$gtable)
invisible(dev.off())

# pheatmap does not go through save_panel, so its realised size is recorded here
# by hand to keep the sizing contract complete. The matrix body is
# cellwidth * ncol by cellheight * nrow, which is PANEL_PT square by construction.
.record_panel_size(file.path(FIG_DIR, "Fig2H_GI_heatmap"),
                   PANEL_PT, PANEL_PT, .hw, .hh, 1L)

message("  Saved Fig2H_GI_heatmap.pdf/.png")


# ============================================================
# SECTION 5: Fig2H-derived R2 GI graph data preparation
# ============================================================
# SuppFig2L and Fig2I are paired network views of the focused R2 GI table used
# in Fig2H, not the broader R1 163-gene significant-GI network.
# ============================================================

message("--- Section 5: Fig2H-derived R2 GI graph prep ---")

# R2_MODULE_COLORS is provided by R/palettes.R (shared with Supp Fig 2L).

r2_gene1_modules <- c(
  Pten = "Growth_Control", Apc = "Growth_Control", Rb1 = "Growth_Control",
  Smad4 = "Growth_Control", Stk11 = "Growth_Control", Tsc2 = "Growth_Control",
  Brca1 = "DNA_Repair", Brca2 = "DNA_Repair", Chek2 = "DNA_Repair",
  Calml3 = "Barrier_ECM", Serpinb5 = "Barrier_ECM",
  Sox10 = "Cell_Identity", Krt15 = "Cell_Identity", Clca2 = "Cell_Identity",
  Tgfbr2 = "Unknown", Kit = "Unknown", Chit1 = "Unknown"
)
r2_gene2_modules <- c(
  Btla = "Immune_Evasion", Cxcr2 = "Immune_Evasion", Cxcr5 = "Immune_Evasion",
  Fcrl6 = "Immune_Evasion", Il6 = "Immune_Evasion", Mpeg1 = "Immune_Evasion",
  Pdcd1lg2 = "Immune_Evasion", Tlr7 = "Immune_Evasion",
  Tnfsf15 = "Immune_Evasion", Cx3cl1 = "Barrier_ECM", Mfap5 = "Barrier_ECM",
  Muc16 = "Barrier_ECM", Pla2g2a = "Barrier_ECM", Pla2r1 = "Barrier_ECM",
  Cdh1 = "Cell_Identity", Hgf = "Growth_Signaling", Mysm1 = "Unknown"
)
r2_modules <- c(r2_gene1_modules, r2_gene2_modules)
r2_modules <- setNames(unname(r2_modules), toupper(names(r2_modules)))

gi2_net <- read.csv(file.path(OUTPUT_DIR, "R2_GI_derived.csv"),
                    stringsAsFactors = FALSE, check.names = FALSE)
gi2_gene_rows <- gi2_net |>
  filter(!.is_nt(Gene1), !.is_nt(Gene2), !is.na(Gene2)) |>
  mutate(gene_A = toupper(Gene1), gene_B = toupper(Gene2))
r2_genes <- sort(unique(c(gi2_gene_rows$gene_A, gi2_gene_rows$gene_B)))
# Same centred GI Z as the heatmap, so a cell that reads strong there is an edge
# here. Previously the network divided by the SD without centring, which made the
# two panels disagree about what "GI Z" meant.
gi2_global_sd <- sd(gi2_gene_rows$GI, na.rm = TRUE)
gi2_global_mean <- mean(gi2_gene_rows$GI, na.rm = TRUE)

gi2_edges <- gi2_gene_rows |>
  # No Count filter; see the note in the heatmap section above.
  mutate(
    GI_Zscore = (GI - gi2_global_mean) / gi2_global_sd,
    abs_GI_Z = abs(GI_Zscore)
  )

strong_gi_partner_counts <- gi2_edges |>
  filter(abs_GI_Z > GI_STRONG_Z_THRESHOLD) |>
  select(gene_A, gene_B) |>
  pivot_longer(cols = everything(), names_to = "endpoint", values_to = "name") |>
  count(name, name = "strong_gi_partners")

r2_single_lfc <- bind_rows(
  gi2_net |> filter(!.is_nt(Gene1)) |>
    transmute(gene = toupper(Gene1), single_lfc = Gene1_NT_LFC_Mean),
  gi2_net |> filter(!.is_nt(Gene2)) |>
    transmute(gene = toupper(Gene2), single_lfc = Gene2_NT_LFC_Mean)
) |>
  filter(!is.na(single_lfc)) |>
  group_by(gene) |>
  summarise(single_lfc = first(single_lfc), .groups = "drop")

r2_vertices <- data.frame(name = r2_genes, stringsAsFactors = FALSE) |>
  left_join(r2_single_lfc, by = c("name" = "gene")) |>
  left_join(strong_gi_partner_counts, by = "name") |>
  mutate(
    strong_gi_partners = coalesce(strong_gi_partners, 0L),
    module_f = factor(ifelse(name %in% names(r2_modules), r2_modules[name], "Unknown"),
                      levels = names(R2_MODULE_COLORS))
  )

write.csv(
  r2_vertices |>
    transmute(
      gene = name,
      module = as.character(module_f),
      strong_gi_partners = strong_gi_partners,
      single_lfc = single_lfc
    ),
  file.path(OUTPUT_DIR, "Fig2I_node_strong_GI_partner_counts.csv"),
  row.names = FALSE
)

message(sprintf(
  "  Fig2H-derived R2 GI graph: %d genes, %d GI edges, %d strong edges (|GI Z| > %.1f)",
  length(r2_genes), nrow(gi2_edges), sum(gi2_edges$abs_GI_Z > GI_STRONG_Z_THRESHOLD),
  GI_STRONG_Z_THRESHOLD
))


# ============================================================
# SECTION 6: Fig2I — GI Network of Fig 2H Genes
# ============================================================

message("--- Fig2I: Fig2H-derived strong-edge GI Network ---")

# Mouse gene-symbol display helper. Internal joins / igraph vertex names
# stay uppercase (to match R1 module assignments and the uppercase-normalized
# r2_modules table), but plotted node labels use the mouse-nomenclature
# Title-case form (Pten, Cdh1, Cx3cl1, ...). Updated 2026-05-02.
to_mouse_symbol <- function(x) {
  ifelse(is.na(x) | x == "",
         x,
         paste0(toupper(substr(x, 1, 1)),
                tolower(substring(x, 2))))
}

gi2_strong_edges <- gi2_edges |>
  filter(abs_GI_Z > GI_STRONG_Z_THRESHOLD)

strong_vertices <- r2_vertices |>
  filter(strong_gi_partners > 0)

write.csv(
  gi2_strong_edges |>
    transmute(gene_A, gene_B, GI, GI_Zscore, abs_GI_Z, Count),
  file.path(OUTPUT_DIR, "Fig2I_strong_GI_edges.csv"),
  row.names = FALSE
)

g_strong <- graph_from_data_frame(
  gi2_strong_edges[, c("gene_A", "gene_B", "GI", "GI_Zscore", "abs_GI_Z")],
  vertices = strong_vertices,
  directed = FALSE
)

tg_strong <- as_tbl_graph(g_strong) |>
  activate(nodes) |>
  mutate(
    module_f = factor(module_f, levels = names(R2_MODULE_COLORS))
  ) |>
  activate(edges) |>
  mutate(
    zscore = GI_Zscore,
    edge_weight_plot = abs_GI_Z
  )

set.seed(123)
p2l <- ggraph(tg_strong, layout = "fr", weights = abs_GI_Z) +
  geom_edge_link(aes(color = zscore, width = edge_weight_plot), alpha = 0.78) +
  scale_edge_color_gradient2(
    low = GI_BLUE, mid = "white", high = GI_RED, midpoint = 0, name = "GI Z"
  ) +
  scale_edge_width(range = c(0.25, 2.2), guide = "none") +
  # Unified node spec shared with Supp Fig 2L (updated 2026-05-02): shape = 21
  # filled circle with thin white outer ring, uniform size, single fill-aesthetic
  # legend so the legend swatch is identical between Supp Fig 2L and Fig 2I.
  geom_node_point(
    aes(fill = module_f),
    shape = 21, color = "white", size = 1.9, stroke = 0.2
  ) +
  # PTEN highlight: thicker black outer ring overlay (matches Supp Fig 2L)
  geom_node_point(
    data = function(x) dplyr::filter(x, name == "PTEN"),
    shape = 21, fill = NA, color = "black", size = 2.4, stroke = 0.45,
    show.legend = FALSE
  ) +
  scale_fill_manual(values = R2_MODULE_COLORS, name = "Functional\nmodule") +
  geom_node_text(
    aes(label = to_mouse_symbol(name),
        fontface = "plain"),
    repel = TRUE, size = pt(FS_LABEL), max.overlaps = Inf,
    segment.alpha = 0.45, segment.size = 0.2,
    box.padding = 0.12, point.padding = 0.07
  ) +
  theme_void(base_size = MIN_FONT_PT) +
  labs(
    title = "Strong GI network of Fig 2H genes",
    subtitle = paste0(
      ecount(g_strong), " strong GI edges (|GI Z| > ", GI_STRONG_Z_THRESHOLD,
      "); ", vcount(g_strong), " connected genes\n",
      "FR layout; node color = functional module; edge color/width = GI Z"
    )
  ) +
  theme(
    plot.title      = element_text(face = "plain", hjust = 0, size = FS_TITLE),
    plot.subtitle   = element_text(hjust = 0, color = "gray40", size = FS_SUBTITLE),
    legend.position = "right",
    legend.title    = element_text(size = FS_LEGEND, face = "plain"),
    legend.text     = element_text(size = FS_LEGEND),
    legend.key.size = unit(6, "pt"),
    plot.margin     = margin(3, 3, 3, 3)
  )

# The Fruchterman-Reingold rendering is retained as an audit output only. Since
# 2026-08-26 the placed Fig2I is the Pten-centred ego layout written by
# scripts/06_fig2I_pten_ego.R, which states the hub claim directly instead of
# leaving it to be counted off a spring solution. This section still writes the
# edge and node tables that both renderings and the contract read.
save_panel(p2l, unplaced_fig("supp_extra_fig2I_fr_layout.pdf"))

message(sprintf(
  "  Saved Fig2I strong-edge FR network | %d connected genes, %d edges with |GI Z| > %.1f",
  vcount(g_strong), ecount(g_strong), GI_STRONG_Z_THRESHOLD
))


# ============================================================
# SECTION 7: SuppFig2Q — Functional Module Epistasis Pattern
# ============================================================
# BIOLOGICAL QUESTION:
#   When genes are grouped by their biological function (cell-autonomous
#   tumor suppressor, DNA repair, ECM barrier, epithelial identity,
#   immune evasion, growth signaling), do certain functional module
#   COMBINATIONS preferentially show buffering (GI < 0) vs. synergy
#   (GI > 0)?
#   This reveals which combinations of biological programs contribute
#   to lung metastasis through epistatic interaction.
#
# INPUT:  output/tables/R2_GI_derived.csv (from 04_r2_derive_gi.R)
#   Same 2nd-round data as Fig2H; filtered to true gene×gene pairs
#   (both Gene1 != NT and Gene2 != NT; no Count filter).
#
# MODULE ASSIGNMENT (literature-curated):
#   Gene1 (Position 1 — cell-autonomous programs):
#     Growth_Control : Pten, Apc, Rb1, Smad4, Stk11, Tsc2
#     DNA_Repair     : Brca1, Brca2, Chek2
#     Barrier_ECM    : Calml3, Serpinb5
#     Cell_Identity  : Sox10, Krt15, Clca2
#     Unknown        : Tgfbr2, Kit, Chit1
#   Gene2 (Position 2 — TME/immune programs):
#     Immune_Evasion : Btla, Cxcr2, Cxcr5, Fcrl6, Il6, Mpeg1,
#                      Pdcd1lg2, Tlr7, Tnfsf15
#     Barrier_ECM    : Cx3cl1, Mfap5, Muc16, Pla2g2a, Pla2r1
#     Cell_Identity  : Cdh1
#     Growth_Signaling: Hgf
#     Unknown        : Mysm1
#
# STATISTIC:
#   For each module-pair combination, count pairs classified as
#   synergy (GI > 0) or buffering (GI < 0). Report percentages.
#   No additional significance threshold — direction is sufficient
#   for exploratory characterization.
#
# OUTPUT:
#   SuppFig2L — module-pair epistasis pattern, Unknown-module pairs excluded.
#   (The with-Unknown variant is retired; not shown in any figure.)
# ============================================================

message("--- SuppFig2Q: Functional Module Epistasis Pattern ---")

# ── 7.1  Module dictionaries ──────────────────────────────
gene1_modules <- c(
  Pten   = "Growth_Control", Apc    = "Growth_Control",
  Rb1    = "Growth_Control", Smad4  = "Growth_Control",
  Stk11  = "Growth_Control", Tsc2   = "Growth_Control",
  Brca1  = "DNA_Repair",     Brca2  = "DNA_Repair",
  Chek2  = "DNA_Repair",
  Calml3 = "Barrier_ECM",    Serpinb5 = "Barrier_ECM",
  Sox10  = "Cell_Identity",  Krt15  = "Cell_Identity",
  Clca2  = "Cell_Identity",
  Tgfbr2 = "Unknown",        Kit    = "Unknown",
  Chit1  = "Unknown"
)

gene2_modules <- c(
  Btla     = "Immune_Evasion", Cxcr2    = "Immune_Evasion",
  Cxcr5    = "Immune_Evasion", Fcrl6    = "Immune_Evasion",
  Il6      = "Immune_Evasion", Mpeg1    = "Immune_Evasion",
  Pdcd1lg2 = "Immune_Evasion", Tlr7    = "Immune_Evasion",
  Tnfsf15  = "Immune_Evasion",
  Cx3cl1   = "Barrier_ECM",   Mfap5    = "Barrier_ECM",
  Muc16    = "Barrier_ECM",   Pla2g2a  = "Barrier_ECM",
  Pla2r1   = "Barrier_ECM",
  Cdh1     = "Cell_Identity",
  Hgf      = "Growth_Signaling",
  Mysm1    = "Unknown"
)

# ── 7.2  Load & classify ──────────────────────────────────
gi2_df <- read.csv(file.path(OUTPUT_DIR, "R2_GI_derived.csv"),
                   stringsAsFactors = FALSE, check.names = FALSE)
gi2_df <- as.data.frame(gi2_df)
gi2_df <- gi2_df[!.is_nt(gi2_df$Gene1) & !.is_nt(gi2_df$Gene2) &
                   !is.na(gi2_df$Gene2), ]

gi2_df$Gene1_Pathway <- gene1_modules[gi2_df$Gene1]
gi2_df$Gene2_Pathway <- gene2_modules[gi2_df$Gene2]
gi2_df <- gi2_df[!is.na(gi2_df$Gene1_Pathway) & !is.na(gi2_df$Gene2_Pathway), ]
gi2_df$interaction_class <- ifelse(gi2_df$GI > 0, "synergy", "buffering")

# Module-pair label (alphabetical order, same-module → "Redundancy")
gi2_df$Module_Interaction <- mapply(function(a, b) {
  pair <- sort(c(a, b))
  if (pair[1] == pair[2]) paste0(pair[1], "_Redundancy")
  else paste(pair[1], pair[2], sep = "_x_")
}, gi2_df$Gene1_Pathway, gi2_df$Gene2_Pathway)

# ── 7.3  Compute per-module-pair statistics ───────────────
counts_m <- as.data.frame(table(gi2_df$Module_Interaction,
                                 gi2_df$interaction_class))
names(counts_m) <- c("Module_Interaction", "interaction_class", "n")

wide_m <- reshape(counts_m,
                  idvar    = "Module_Interaction",
                  timevar  = "interaction_class",
                  direction = "wide")
names(wide_m) <- gsub("n\\.", "", names(wide_m))
for (col in c("buffering", "synergy")) {
  if (!col %in% names(wide_m)) wide_m[[col]] <- 0
}
wide_m$total        <- wide_m$buffering + wide_m$synergy
wide_m$synergy_pct  <- wide_m$synergy   / wide_m$total * 100
wide_m$buffering_pct<- wide_m$buffering / wide_m$total * 100
summary_m <- wide_m[order(wide_m$synergy_pct), ]

write.csv(summary_m, file.path(OUTPUT_DIR, "module_epistasis_summary.csv"),
          row.names = FALSE)

# ── 7.4  Panel plot helper ────────────────────────────────
make_epistasis_barplot <- function(smry) {
  # Long format for stacked bar
  plot_long <- rbind(
    data.frame(Module_Interaction = smry$Module_Interaction,
               class = "Buffering (GI<0)", pct = smry$buffering_pct),
    data.frame(Module_Interaction = smry$Module_Interaction,
               class = "Synergy (GI>0)",   pct = smry$synergy_pct)
  )
  plot_long$Module_Interaction <- factor(plot_long$Module_Interaction,
                                          levels = smry$Module_Interaction)

  lbl <- smry
  lbl$Module_Interaction <- factor(lbl$Module_Interaction,
                                    levels = smry$Module_Interaction)
  # The stacked bar draws synergy first from x = 0 and buffering after it, so
  # each label has to be centred inside its OWN segment. The previous ordering
  # assumed the reverse and put both labels inside the synergy segment whenever
  # synergy dominated (e.g. Cell_Identity x Growth_Control, 80/20).
  lbl$syn_x  <- lbl$synergy_pct / 2
  lbl$buff_x <- lbl$synergy_pct + lbl$buffering_pct / 2

  ggplot(plot_long, aes(pct, Module_Interaction, fill = class)) +
    geom_col(alpha = 0.85, color = "black", linewidth = LW_THIN) +
    geom_text(data = subset(lbl, synergy_pct > 5),
              aes(x = syn_x, y = Module_Interaction,
                  label = paste0(round(synergy_pct), "%")),
              inherit.aes = FALSE, color = "white",
              fontface = "plain", size = pt(FS_LABEL)) +
    geom_text(data = subset(lbl, buffering_pct > 5),
              aes(x = buff_x, y = Module_Interaction,
                  label = paste0(round(buffering_pct), "%")),
              inherit.aes = FALSE, color = "white",
              fontface = "plain", size = pt(FS_LABEL)) +
    # Per-bar n is deliberately NOT drawn: several combinations rest on very few
    # pairs (the 100% bars can be n = 2), and the denominators are reported in
    # the supplementary legend instead, which is where the placed panel carries
    # them. Do not reintroduce an n column here without re-placing the panel.
    scale_fill_manual(values = c("Buffering (GI<0)" = "#3498DB",
                                  "Synergy (GI>0)"  = "#E74C3C")) +
    scale_x_continuous(limits = c(0, 100), expand = c(0, 0),
                       breaks = c(0, 25, 50, 75, 100)) +
    labs(
      title = "Epistasis by functional module",
      x = "Percentage (%)", y = NULL, fill = NULL
    ) +
    theme_panel(grid_y = FALSE) +
    theme(
      axis.text.y     = element_text(size = FS_AXIS_TEXT, face = "plain"),
      legend.position = "bottom",
      legend.key.size = unit(5, "pt")
    )
}

summary_nounknown <- summary_m[!grepl("Unknown", summary_m$Module_Interaction), ]
p2l <- make_epistasis_barplot(summary_nounknown)
save_panel(p2l, supp_fig("SuppFig2Q_module_epistasis.pdf"))

message(sprintf("  Saved SuppFig2Q_module_epistasis.pdf/.png -> _supplementary/ | %d combinations, %d pairs",
                nrow(summary_nounknown), sum(summary_nounknown$total)))


# ============================================================
# END
# ============================================================
message("\n=== Main-figure R panels saved to: ", FIG_DIR, " ===\n")
message("This script (Step 3) produces main Fig2C (PCA), Fig2D (rank), Fig2G (volcano),")
message("  Fig2H (GI heatmap), Fig2I (GI network), plus SuppFig2Q (module epistasis).")
message("Step 1 (01_prepare_r1_gi_tables.R) produces Fig2E (guide LFC) + R1 tables;")
message("Step 2 (02_r1_modules.R) produces SuppFig2J (spectral) + SuppFig2K (forest).")
message("Full workflow: Rscript scripts/make_figure_2.R")

log_session("03_main_panels")
